services:
  file-uploader:
    container_name: kaspi-file-uploader
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - app/file-uploader/.env
    restart: unless-stopped
    networks:
      kaspi_minio_kaspi_lab_net:
        ipv4_address: 10.50.0.43

networks:
  kaspi_minio_kaspi_lab_net:
    external: true
